twenty-three-23/peech

src/main/java/com/twentythree/peech/api/ScriptController.java, src/main/java/com/twentythree/peech/api/SwaggerScriptInterface.java, src/main/java/com/twentythree/peech/dto/AllDefaultTimeResponseDTO.java
=> Refactor: TT-36 remove operation

build.gradle, src/main/resources/application.properties, src/main/resources/application.yml
build.gradle에서 MySQL 드라이버를 넣어주고
applicaiton.properties를 yml로 바꾼후 DB 세팅과 임시 로깅 세팅을 마쳤다.
=> TT-40 MySQL build.gradle and yml 파일 설정

build.gradle, src/main/java/com/twentythree/peech/config/RedisConfig.java, src/main/resources/application.properties, src/main/resources/application.yml
1. build.gradle에서 spring-data-redis 넣음
2. applicaiton.properties를 yml로 변경하고 spring.data.redis에서 host, port, password를 설정
3. RedisConfig class를 만들어 bean등록
=> TT-48 Redis 환경 설정

src/main/java/com/twentythree/peech/script/ScriptController.java, src/main/java/com/twentythree/peech/script/SwaggerScriptInterface.java, src/main/java/com/twentythree/peech/script/dto/DefaultTimeResponseDTO.java, src/main/java/com/twentythree/peech/script/dto/ParagraphRequestDTO.java, src/main/java/com/twentythree/peech/script/dto/ParagraphResponseDTO.java, src/main/java/com/twentythree/peech/script/dto/ScriptRequestDto.java
api라고 정의된 패키리를 도메인이에 맞춰 script 패키로 만들어 이전
common 패키지를 만들어 공통되는 코드들을 관리
=> TT-52 패키지 구조 변경

.gitignore, build.gradle, src/main/java/com/twentythree/peech/PeechApplication.java, src/main/java/com/twentythree/peech/common/domain/BaseTimeEntity.java
엔티티에서 공통되는 timestamp를 가지는 base entity를 MappedSuperclass로 생성
=> TT-53 base entity 생성

src/main/java/com/twentythree/peech/common/dto/ErrorDTO.java, src/main/java/com/twentythree/peech/common/exception/BaseException.java
모든 컨트롤러에 적용되는 기본 exceptionHandler를 만들었다. 
그 과정에서 필요한 ErrorDTO를 만들어 에러 메시지를 담을 수 있게 했다.
=> TT-55 전체에 적용되는 기본 ExceptionHandler 만들기

src/main/java/com/twentythree/peech/user/domain/UserEntity.java
user 패키지에 domain 패키지 생성 후 userEntity 클래스를 domain 패키지로 이동
=> TT-49 user 패키지에 domain 패키지 생성

src/main/java/com/twentythree/peech/user/repository/UserRepository.java
userRepository 를 JpaRepository를 이용해 생성
=> TT-60 userRepository 생성

src/main/java/com/twentythree/peech/user/domain/UserEntity.java, src/main/java/com/twentythree/peech/user/dto/CreateUserRequestDTO.java, src/main/java/com/twentythree/peech/user/repository/UserRepository.java, src/main/java/com/twentythree/peech/user/service/UserService.java, src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
deviceId를 통해 유저를 생성
deviceId로 이미 가입된 유저인지 확인
리턴으로 userId를 전송
=> TT-66 유저 생성 로직

src/main/java/com/twentythree/peech/script/domain/VersionEntity.java, src/main/java/com/twentythree/peech/script/domain/VersionPk.java
버전을 관리하는 entity,pk는 major version, minor version 이고,package entity의 package id와 user id를 컬럼으로 가진다.
=> TT-73 VERSION entity

src/main/java/com/twentythree/peech/script/domain/ScriptEntity.java
ofCreateSTTScript 팩토리 메소드에서 totalExceptTime 파라미터를 totalRealTime으로 변경
팩토리 메소드에서 DType이 잘 못 입력되었을때 IllegalArgumentException 에러 발생
=> TT-76 script entity 팩토리 메소드 파라미터 수정

src/main/java/com/twentythree/peech/script/repository/PackageRepository.java, src/main/java/com/twentythree/peech/script/repository/SentenceRepository.java
=> feat: package repository 생성

src/main/java/com/twentythree/peech/script/repository/PackageRepository.java, src/main/java/com/twentythree/peech/script/repository/SentenceRepository.java
=> feat: sentence repository 생성

src/main/java/com/twentythree/peech/script/domain/PackageEntity.java, src/main/java/com/twentythree/peech/script/domain/ScriptEntity.java, src/main/java/com/twentythree/peech/script/domain/SentenceEntity.java, src/main/java/com/twentythree/peech/script/domain/VersionEntity.java, src/main/java/com/twentythree/peech/user/domain/UserEntity.java
=> TT-94 db relations

src/main/java/com/twentythree/peech/auth/config/ArgumentResolverConfig.java, src/main/java/com/twentythree/peech/auth/dto/LoginUserId.java, src/main/java/com/twentythree/peech/auth/dto/UserIdDTO.java, src/main/java/com/twentythree/peech/auth/resolver/AuthArgumentResolver.java, src/main/java/com/twentythree/peech/script/controller/SwaggerThemeInterface.java, src/main/java/com/twentythree/peech/script/controller/ThemeController.java, src/main/java/com/twentythree/peech/script/domain/ThemeEntity.java, src/main/java/com/twentythree/peech/script/domain/VersionEntity.java, src/main/java/com/twentythree/peech/script/dto/request/ThemeTitleRequestDTO.java, src/main/java/com/twentythree/peech/script/dto/response/ThemeIdResponseDTO.java, src/main/java/com/twentythree/peech/script/repository/PackageRepository.java, src/main/java/com/twentythree/peech/script/repository/ThemeRepository.java, src/main/java/com/twentythree/peech/script/service/ThemeService.java, src/main/java/com/twentythree/peech/user/domain/UserEntity.java
Package에서 Theme으로 명명 변경
쿠키에서 userId를 가져오는 argumentResolver 추가
userId와 themeTitle을 이용해 ThemeEntity생성
=> TT-98 Theme 생성

src/main/java/com/twentythree/peech/script/controller/ScriptController.java, src/main/java/com/twentythree/peech/script/controller/SwaggerScriptInterface.java, src/main/java/com/twentythree/peech/script/controller/SwaggerThemeInterface.java, src/main/java/com/twentythree/peech/script/controller/ThemeController.java, src/main/java/com/twentythree/peech/script/dto/MajorScriptDTO.java, src/main/java/com/twentythree/peech/script/dto/MinorScriptDTO.java, src/main/java/com/twentythree/peech/script/dto/ThemeDTO.java, src/main/java/com/twentythree/peech/script/dto/response/MajorScriptsResponseDTO.java, src/main/java/com/twentythree/peech/script/dto/response/MinorScriptsResponseDTO.java, src/main/java/com/twentythree/peech/script/dto/response/ThemesResponseDTO.java, src/main/java/com/twentythree/peech/script/repository/ScriptRepository.java, src/main/java/com/twentythree/peech/script/service/ScriptService.java, src/main/java/com/twentythree/peech/script/service/ThemeService.java, src/main/resources/data.sql, src/test/java/com/twentythree/peech/script/service/ThemeServiceTest.java
userId를 이용해 Theme 조회
themeid를 이용해 major대본 조희
majorVersion, themeId를 이용해 minor대본 조회
=> TT-102 history

src/main/java/com/twentythree/peech/script/controller/ScriptController.java, src/main/java/com/twentythree/peech/script/controller/SwaggerScriptInterface.java, src/main/java/com/twentythree/peech/script/controller/ThemeController.java, src/main/java/com/twentythree/peech/script/dto/request/ParagraphsRequestDTO.java, src/main/java/com/twentythree/peech/script/dto/response/SaveScriptAndSentenceResponseDTO.java, src/main/java/com/twentythree/peech/script/dto/response/SaveScriptAndSentencesResponseDTO.java, src/main/java/com/twentythree/peech/script/service/ScriptSentenceFacade.java, src/main/java/com/twentythree/peech/script/service/ScriptService.java, src/main/java/com/twentythree/peech/user/controller/UserController.java
stateless를 유지 할 수 있는 방향으로 api uri path구조를 변경해 보았습니다.
=> TT-169 controller 계층 구조 변경

build.gradle, src/main/java/com/twentythree/peech/common/utils/JWTUtils.java, src/main/java/com/twentythree/peech/user/controller/SwaggerUserController.java, src/main/java/com/twentythree/peech/user/controller/UserController.java, src/main/java/com/twentythree/peech/user/dto/response/CreateUserResponseDTO.java, src/main/java/com/twentythree/peech/user/service/UserService.java, src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java, src/main/resources/application.yml
secretKey를 환경변수로 설정 후 base64로 인코딩해서 jwt를 생성 jwt의 payload에는 "sub": "LoginToken", "userId":{userId}가 생성된다.
=> TT-161 userId를 토큰에 담아 응답

.github/workflows/cicd_dev.yml, build.gradle, src/main/java/com/twentythree/peech/auth/config/ArgumentResolverConfig.java, src/main/java/com/twentythree/peech/auth/resolver/AuthArgumentResolver.java, src/main/java/com/twentythree/peech/common/utils/JWTUtils.java, src/main/java/com/twentythree/peech/user/controller/SwaggerUserController.java, src/main/java/com/twentythree/peech/user/controller/UserController.java, src/main/java/com/twentythree/peech/user/dto/response/CreateUserResponseDTO.java, src/main/java/com/twentythree/peech/user/service/UserService.java, src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java, src/main/resources/application.yml, src/test/java/com/twentythree/peech/script/service/ThemeServiceTest.java
parseJWT에 토큰을 넣으면 jwt를 해독해 전달한다.
쿠키에서 꺼낸 jwt토큰을 parseJWT에서 해독해 userId를 꺼내 전달한다.
=> TT-162 userid to token

.github/workflows/cicd_dev.yml
=> ! TT-173 cicd jwt env

src/main/java/com/twentythree/peech/user/controller/SwaggerUserController.java, src/main/java/com/twentythree/peech/user/controller/UserController.java, src/main/java/com/twentythree/peech/user/dto/response/UserIdTokenResponseDTO.java, src/main/java/com/twentythree/peech/user/service/UserService.java, src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
1. user 생성에서 jwt 토큰 생성 로직을 service로 이동
2. user 생성 controller에서 response dto 이름 변경
3. deviceId를 통해 가입된 유저가 있는 지 확인
4. 가입된 유저가 있다면 토큰 재발급
=> TT-171 re issuance user token

src/main/java/com/twentythree/peech/common/dto/UserAlreadyExistErrorVO.java, src/main/java/com/twentythree/peech/common/exception/BaseException.java, src/main/java/com/twentythree/peech/common/exception/UserAlreadyExistException.java, src/main/java/com/twentythree/peech/user/service/UserService.java, src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
이미 가입된 유저의 경우 UserAlreadyExistException을 만들어 throw 한 후,
BaseException에서 UserAlreadyExistException이 발생한 경우 401 에러를 응답함
=> TT-207 이미 가입된 유저 예외처리 [0.5/0.5]

src/main/java/com/twentythree/peech/auth/resolver/AuthArgumentResolver.java
token을 header의 cookie에서 가져오다 header의 Authorization에서 가져옴
=> TT-210 token을 header의 Authorization에서 조회

.github/workflows/cicd_dev.yml
self-hosted runner에서 외부에서 ssh에 접속하게 변경
=> TT-208 cicd update

.github/workflows/cicd_dev.yml
=> TT-208 actions/checkout

src/main/java/com/twentythree/peech/config/RedisConfig.java, src/main/java/com/twentythree/peech/config/ScriptRedisTemplate.java, src/main/java/com/twentythree/peech/script/cache/CacheTemplate.java, src/main/java/com/twentythree/peech/script/cache/RedisTemplateImpl.java, src/main/java/com/twentythree/peech/script/dto/SaveRedisSentenceInfoDto.java, src/main/java/com/twentythree/peech/script/dto/SaveRedisUserSentenceListDto.java, src/test/java/com/twentythree/peech/script/service/RedisTemplateImplTest.java, src/test/java/com/twentythree/peech/script/service/ScriptRedisTemplateImplTest.java
Redis 환경 세팅 및 STT결과를 반환할 형태의 DTO를 거친 후 Redis에 저장되는 로직 수행
=> TT-118 Redis 세팅 및 STT 문장 save 로직

src/main/java/com/twentythree/peech/script/repository/ThemeRepository.java, src/main/java/com/twentythree/peech/script/service/ThemeService.java, src/main/resources/data.sql
JpaRepository의 잘못된 사용으로 조회 메소드를 만들었다.
=> !TT-216 themes 조회시 theme이 하나만 조회됨

src/main/java/com/twentythree/peech/script/controller/ScriptController.java, src/main/java/com/twentythree/peech/script/controller/SwaggerScriptInterface.java, src/main/java/com/twentythree/peech/script/domain/SentenceEntity.java, src/main/java/com/twentythree/peech/script/dto/ModifiedParagraphDTO.java, src/main/java/com/twentythree/peech/script/dto/ParagraphAndExpectedTimeDTO.java, src/main/java/com/twentythree/peech/script/dto/ParagraphDTO.java, src/main/java/com/twentythree/peech/script/dto/ParagraphId.java, src/main/java/com/twentythree/peech/script/dto/RedisSentenceDTO.java, src/main/java/com/twentythree/peech/script/dto/RedisSentencesPerParagraphId.java, src/main/java/com/twentythree/peech/script/dto/SentenceDTO.java, src/main/java/com/twentythree/peech/script/dto/SentenceId.java, src/main/java/com/twentythree/peech/script/dto/request/ModifiedScriptRequestDTO.java, src/main/java/com/twentythree/peech/script/dto/response/ModifiedScriptResponseDTO.java, src/main/java/com/twentythree/peech/script/dto/response/ModifyScriptResponseDTO.java, src/main/java/com/twentythree/peech/script/repository/ScriptInMemoryRepository.java, src/main/java/com/twentythree/peech/script/service/ScriptService.java
In-Memory DB에서 데이터를 조회하는 행위를 interface만 만들어 사용
1. 수정된 문단들에서
1-1. 새롭게 생성된 문단은 예상 시간을 계산한다.
2. 기존의 문단에서 수정이 일어났다면 문단내의 문장들을 기존의 문장들과 비교한다.
2-1. 새롭게 추가되거나 수정된 문장이면 예상시간을 계산해 추가한다.
2-2. 예상 시간과 실제 시간을 더해 반환한다.
=> TT-205 modify script [2/8]

src/main/java/com/twentythree/peech/config/RedisConfig.java, src/main/java/com/twentythree/peech/config/ScriptRedisTemplate.java, src/main/java/com/twentythree/peech/script/cache/CacheService.java, src/main/java/com/twentythree/peech/script/cache/RedisTemplateImpl.java, src/main/java/com/twentythree/peech/script/dto/RedisSentenceDTO.java, src/test/java/com/twentythree/peech/script/service/ScriptRedisTemplateImplTest.java
Redis에 저장한 데이터 조회하는 기능 추가
redis 조회 과정 개념 적용시간 + 테스트코드 바뀐 convention에 맞춰서 작성하는데 추가 시간이 소요됨
=> feat: TT-222 Redis 조회로직 추가 + 테스트 코드 수정 [2/4]

.gitignore, src/main/java/com/twentythree/peech/auth/interceptor/AuthInterceptor.java, src/main/java/com/twentythree/peech/common/interceptor/RequestLogInterceptor.java, src/main/java/com/twentythree/peech/config/interceptor/AuthInterceptorConfig.java, src/main/java/com/twentythree/peech/config/interceptor/LogInterceptorConfig.java, src/main/resources/application.yml, src/main/resources/spring-logback.xml
AuthInterceptor를 통해 userId를 request에 담고,
RequestLogIntreceptor를 통해서 userId, path, uuid를 출력하고 logs/ 밑에 로그를 파일로 저장한다.
=> TT-223 log 수집 [4/6]

src/main/java/com/twentythree/peech/script/domain/ScriptEntity.java, src/main/java/com/twentythree/peech/script/domain/VersionEntity.java, src/main/java/com/twentythree/peech/script/domain/VersionPk.java, src/main/java/com/twentythree/peech/script/service/ScriptService.java
VersionEntity에서 themeId를 복합키로 추가
=> !TT-232 VersionEntity 복합키 설정

src/main/java/com/twentythree/peech/script/domain/ScriptEntity.java, src/main/java/com/twentythree/peech/script/domain/VersionEntity.java
VersionEntity에서 themeId를 DB에 반영하지 않게 하고 ThemeEntity를 반영되게 변경 
ScriptEntity에서 themeId를 가지지 않게 변경
=> TT-234 ThemeEntity DB 반영 값 변경 및 ScriptEntity fk 설정

src/main/java/com/twentythree/peech/script/domain/SentenceEntity.java, src/main/java/com/twentythree/peech/script/service/SentenceService.java
1. SentenceEntity의 생성사에 값들을 채워넣는 로직을 추가
2. SentenceService에서 문장을 나눌때 \\.\\s*으로 나누기
3. 문장 마지막에 . 찍어주기
=> !TT-236 문장 생성이 안되는 버그

src/main/java/com/twentythree/peech/script/domain/ScriptEntity.java, src/main/java/com/twentythree/peech/script/domain/SentenceEntity.java, src/main/java/com/twentythree/peech/script/repository/ScriptRepository.java
1. ScriptEntity에서 ThemeId또한 fk로 사용
2. findMajorScriptByThemeId에서 join에 themeId 사용
=> !TT-237 메이저 스크립트 조회 불가

src/main/java/com/twentythree/peech/script/repository/ScriptRepository.java
findMajorScriptByThemeId 에서 themeId를 where조건에 걸어줌
=> !TT-237 테마 아래에 모든 메이저 버전이 생성됨

src/main/java/com/twentythree/peech/script/controller/ScriptController.java, src/main/java/com/twentythree/peech/script/controller/SwaggerScriptInterface.java, src/main/java/com/twentythree/peech/script/repository/ScriptRepository.java, src/main/java/com/twentythree/peech/script/service/ScriptService.java
클라이언트로부터 themeId, MajorVersion, MinorVersion을 pathVariable로 받으면 해당 버전의 스크립트를 반환한다
=> feat: TT-226 MinorScriptDetail 반환

src/main/java/com/twentythree/peech/script/controller/ScriptController.java, src/main/java/com/twentythree/peech/script/controller/SwaggerScriptInterface.java, src/main/java/com/twentythree/peech/script/dto/response/MinorDetailScriptDTO.java, src/main/java/com/twentythree/peech/script/dto/response/ParagraphDetail.java, src/main/java/com/twentythree/peech/script/repository/ScriptRepository.java, src/main/java/com/twentythree/peech/script/repository/SentenceRepository.java, src/main/java/com/twentythree/peech/script/service/ScriptSentenceFacade.java, src/main/java/com/twentythree/peech/script/service/ScriptService.java, src/main/java/com/twentythree/peech/script/service/SentenceService.java
- 사용자로부터 themeId, MajorVersion, MinorVersion을 입력받게 되면 해당 스크립트의 전체 시간 및 문단별로 시간과 내용을 응답해줌
+ 쿼리문 작성시 @Param 어노테이션을 안쓰면 인식을 못하는 문제가 발생하는데 저만 그런건가요? 그래서 일단 넣은 상태로 push 합니다!
=> fix: TT-242 minor detail 정정된 컨벤션에 맞도록 수정함

src/main/java/com/twentythree/peech/script/dto/MajorScriptDTO.java, src/main/java/com/twentythree/peech/script/dto/response/ThemesResponseDTO.java, src/main/java/com/twentythree/peech/script/repository/VersionRepository.java, src/main/java/com/twentythree/peech/script/service/ScriptService.java
count query를 활용하여 major버전 아래의 minor version이 0이 아닌 것들의 개수를 조회한다.
=> TT-174 메이저 버전들을 조회할 때 minor script의 개수를 포함한다 [1/1]

src/main/java/com/twentythree/peech/script/controller/ScriptController.java, src/main/java/com/twentythree/peech/script/controller/SwaggerScriptInterface.java, src/main/java/com/twentythree/peech/script/dto/ParagraphContent.java, src/main/java/com/twentythree/peech/script/dto/response/ParagraphsResponseDTO.java, src/main/java/com/twentythree/peech/script/service/ScriptService.java
1. 응답을 위한 DTO 생성
2. scriptId를 이용해 sentence를 가져온다
3. sentences를 paragraphId, sentenceOrder순서로 정렬한다.
4. 같은 paragraphId일때 content를 합친다.
5. 대본id를 통해 문단을 응답 받는 컨트롤러 생성
=> TT-241 대본Id를 통한 문단 조회

src/main/java/com/twentythree/peech/script/stt/dto/request/STTRequestDto.java, src/main/java/com/twentythree/peech/script/stt/service/RequestClovaSpeechApiService.java
음성파일을 받은 naming 불일치로 인한 문제였으며 서버쪽에서 name을 변경하며 해결함
=> !bug: TT-259 클라이언트로부터 받은 파일 입력이 처리안되는 오류 해결

src/main/java/com/twentythree/peech/usagetime/controller/SwaggerUsageTimeController.java, src/main/java/com/twentythree/peech/usagetime/controller/UsageTimeController.java, src/main/java/com/twentythree/peech/usagetime/domain/UsageTimeEntity.java, src/main/java/com/twentythree/peech/usagetime/dto/AudioFileRequestDTO.java, src/main/java/com/twentythree/peech/usagetime/dto/response/CheckRemainingTimeResponseDTO.java, src/main/java/com/twentythree/peech/usagetime/dto/response/RemainingTimeResponseDTO.java, src/main/java/com/twentythree/peech/usagetime/repository/UsageTimeRepository.java, src/main/java/com/twentythree/peech/usagetime/service/UsageTimeService.java, src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
usageTimeId는 auto increment
remainingTime은 기본 값으로 9000(150분)을 가진다.
userId로 usageTimeEntity 조회
usageTimeEntity의 remaining time 업데이트
subUsageTimeByAudio: 오디오 파일을 받아 시간을 측정하고 remaining time에서 줄이기
subUsageTimeByTimePerSecond: Long(초)으로 시간을 입력받아 remaining time에서 줄이기
getUsageTime: 남은 시간 측정로직
checkRemainingTime: 시간을 입력 받으면 남은시간과 비교해 사용시간이 부족한지 충분한지 알려주는 로직
checkRemainingTime: 음성 시간을 Long으로 받고 남은 시간과 비교하여 결과를 응답
getUsageTime: userId로 UsageTimeEntity 조회
=> TT-245 사용 시간 기초로직 구현

src/main/java/com/twentythree/peech/common/utils/ScriptUtils.java, src/main/java/com/twentythree/peech/usagetime/constant/ConstantValue.java, src/main/java/com/twentythree/peech/usagetime/controller/SwaggerUsageTimeController.java, src/main/java/com/twentythree/peech/usagetime/controller/UsageTimeController.java, src/main/java/com/twentythree/peech/usagetime/dto/RemainingTimeDTO.java, src/main/java/com/twentythree/peech/usagetime/dto/response/TextAndSecondTimeResponseDTO.java, src/main/java/com/twentythree/peech/usagetime/repository/UsageTimeRepository.java, src/main/java/com/twentythree/peech/usagetime/service/UsageTimeService.java
남은 시간 조회에서 응답 스펙 변경 
{
"remainingTime" : {"text": "HH시간 MM분 SS초", "second": Long}
}
최대 음성 녹음 가능 시간 조회
=> TT-271 남은 시간 조회 응답 스펙변경 및 최대 음성 녹음 가능 시간 조회

src/main/java/com/twentythree/peech/script/domain/ScriptEntity.java, src/main/java/com/twentythree/peech/usagetime/domain/UsageTimeEntity.java, src/main/resources/data.sql
data.sql에 테스트 데이터 추가
usage_time entity 오타 수정
Enum을 db에 String으로 저장하게 수정
=> TT-273 테스트 데이터 추가

src/main/java/com/twentythree/peech/script/cache/RedisTemplateImpl.java
=> fix: TT-277 redis 데이터 저장 및 조회시 key naming 변경

src/main/java/com/twentythree/peech/script/cache/RedisTemplateImpl.java, src/main/java/com/twentythree/peech/script/domain/SentenceEntity.java, src/main/java/com/twentythree/peech/script/dto/NowStatus.java, src/main/java/com/twentythree/peech/script/service/ScriptService.java, src/main/java/com/twentythree/peech/script/stt/service/CreateSTTResultService.java
- enum 값들 대문자로 변환
- 문장이 저장이 안되는 문제 해결
=> fix: 기타 자잘한 네이밍 및 sentence_content 타입변경

.github/workflows/cicd_dev.yml
dev ec2 로컬에 설치된 redis와 연결해주는 코드
=> TT-288 dev환경에 redis 세팅

src/main/java/com/twentythree/peech/common/utils/ScriptUtils.java, src/main/java/com/twentythree/peech/script/dto/response/ModifyScriptResponseDTO.java, src/main/java/com/twentythree/peech/script/service/ScriptService.java
수정 대본 응답에서 전체 시간과 대본 아이디 추가
대본에 걸리는 시간에 milesecond도 소수점 두번째 자리까지 출력
=> TT-286 대본 수정 응답 구성 변경

src/main/java/com/twentythree/peech/script/service/ScriptService.java
start, end로 기능 별로 코드의 시작과 끝을 명시 해 줌
=> TT-292 문장 수장 코드 주석 추가

.github/workflows/cd_prod.yml, .github/workflows/ci_prod.yml
=> TT-186 prod ci cd

.github/workflows/cd_prod.yml, .github/workflows/ci_prod.yml, .github/workflows/cicd_dev.yml, Dockerfile, src/main/resources/application.yml, src/main/resources/spring-logback.xml
도커 볼륨을 생성하고 도커 이미지와 연결, 도커 볼륨 파일에 777모드로 권한 변경
=> TT-252 docker volume

src/main/java/com/twentythree/peech/script/controller/ScriptController.java, src/main/java/com/twentythree/peech/script/controller/SwaggerScriptInterface.java, src/main/java/com/twentythree/peech/script/service/SaveModifyScriptService.java
- userId를 기반으로 sentenceIdList 가져와서 redis에 저장된 sentence정보 추출
- sentence 정보들을 기반으로 db script, sentence 테이블에 저장 이때 Dtype은 INPUT임
=> TT-297 최종 수정된 대본을 db에 저장

src/main/java/com/twentythree/peech/common/exception/BaseException.java, src/main/java/com/twentythree/peech/script/domain/ScriptEntity.java, src/main/java/com/twentythree/peech/script/domain/ThemeEntity.java, src/main/java/com/twentythree/peech/script/domain/VersionEntity.java, src/main/java/com/twentythree/peech/script/repository/ScriptRepository.java, src/main/java/com/twentythree/peech/script/repository/ThemeRepository.java, src/main/java/com/twentythree/peech/script/service/ScriptService.java, src/main/java/com/twentythree/peech/script/service/ThemeService.java, src/main/java/com/twentythree/peech/user/domain/UserEntity.java
양방향 참조를 삭제
양방향 참조를 하고 있는 코드는 dao를 통한 접근으로 변경
=> TT-272 엔티티 양방향 참조 삭제

src/main/java/com/twentythree/peech/script/domain/SentenceEntity.java, src/main/java/com/twentythree/peech/script/stt/dto/request/STTRequestDto.java, src/main/java/com/twentythree/peech/script/stt/service/ProcessSTTService.java
- 프론트로부터 계산된 시간을 기반으로 사용자가 사용할 수 있는 시간 차감하도록 임시 변경
- 안쓰는 script 팩토리 메소드 삭제
=> TT-268 stt request dto 수정

build.gradle
elb 사용을 위한 health check용도로 spring actuator 설치
=> TT-302 spring actuator

src/main/java/com/twentythree/peech/script/controller/ScriptController.java, src/main/java/com/twentythree/peech/script/controller/SwaggerScriptInterface.java, src/main/java/com/twentythree/peech/script/service/SaveModifyScriptService.java
기존의 대본완료 문구형태에서 생성된 scriptId를 반환하도록 바꿈
=> TT-297 scriptId 반환하도록 수정

src/main/java/com/twentythree/peech/usagetime/constant/ConstantValue.java, src/main/java/com/twentythree/peech/usagetime/service/UsageTimeService.java
최대 녹음 시간 15분으로 변경
최대 녹음 시간에서 5초의 여유
=> TT-299 녹음 가능 최대 시간 수정

src/main/java/com/twentythree/peech/script/service/SaveModifyScriptService.java
=> TT-297 script 문장 순서 이상함

src/main/java/com/twentythree/peech/script/domain/InputAndSttType.java, src/main/java/com/twentythree/peech/script/domain/ScriptEntity.java, src/main/java/com/twentythree/peech/script/domain/SentenceEntity.java, src/main/java/com/twentythree/peech/script/service/SaveModifyScriptService.java
기존의 팩토리얼 함수를 건드리지 않게 하고자 modify타입 추가
추후 리팩토링 예정
=> TT-297 dtype modify 추가

src/main/java/com/twentythree/peech/script/stt/dto/response/STTParagraphDTO.java, src/main/java/com/twentythree/peech/script/stt/service/CreateSTTResultService.java, src/main/java/com/twentythree/peech/script/stt/service/ProcessSTTService.java, src/main/java/com/twentythree/peech/usagetime/dto/response/CheckRemainingTimeResponseDTO.java, src/main/java/com/twentythree/peech/usagetime/service/UsageTimeService.java
- 로직 생성에 따른 예외처리를 위해 boolean 변수 추가함
- 측정 결과 빠름, 적정, 느림으로 문단별로 반환해줌
=> TT-258 측정 결과 추가, 앞단에 녹음시간 로직 추가

src/main/java/com/twentythree/peech/script/stt/dto/response/STTParagraphDTO.java
=> TT-258 측정 시간 변수명 변경

src/main/java/com/twentythree/peech/script/controller/ScriptController.java, src/main/java/com/twentythree/peech/script/service/ScriptSentenceFacade.java
- paragraphId로 묶은 후 -> sentenceOrder를 기준으로 정렬하는 방식으로 변경
=> TT-334 수정 스크립트 문단별로 조회 시 순서가 정렬되지 않는 문제

src/main/java/com/twentythree/peech/script/domain/ScriptEntity.java, src/main/java/com/twentythree/peech/script/service/SaveModifyScriptService.java, src/main/java/com/twentythree/peech/script/service/ScriptService.java, src/main/java/com/twentythree/peech/script/service/SentenceService.java, src/main/java/com/twentythree/peech/script/stt/service/CreateParagraghService.java, src/main/java/com/twentythree/peech/script/stt/service/ProcessSTTService.java, src/main/java/com/twentythree/peech/usagetime/dto/response/CheckRemainingTimeResponseDTO.java, src/main/java/com/twentythree/peech/usagetime/service/UsageTimeService.java
- scriptEntity 생성시 전체 예상시간을 넣어줌
- 전체 예상시간을 가져오는 로직 추가
- 기존의 필요없던 로직 삭제
- stt 시간 기반으로 사용자 시간 차감하도록 수정
=> bug: TT-334 예상시간 조회시 null 오류 해결

.github/workflows/cd_prod.yml
로깅을해서 수집한 파일을 도커 볼륨으로 연동시켜 영구 저장
=> TT-350 개발 서버 로깅 볼륨 설정

.github/workflows/cd_prod.yml
=> TT-350 도커 볼륨 설정

.github/workflows/cd_prod.yml
logs 디렉토리를 logs 볼륨과 연결
쓰기 권한 부여
=> TT-350 logs 디렉토리에 쓰기 권한 부여

.github/workflows/cicd_dev.yml
docker pull하는데 시간이 오래걸려 연결이 종료됨
-o ServerAliveInterval=60 로 해결
=> TT-350 ssh 연결이 끊김

src/main/java/com/twentythree/peech/user/client/KakaoLoginClient.java, src/main/java/com/twentythree/peech/user/dto/KakaoAccount.java, src/main/java/com/twentythree/peech/user/dto/response/KakaoGetUserEmailResponseDTO.java, src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java, src/main/java/com/twentythree/peech/user/validator/UserValidator.java, src/main/java/com/twentythree/peech/user/validator/UserValidatorImpl.java
객체 필드에 오타 해결
헤더에 content-type추가
jsonProperty로 json 매핑 및 빈 생성자 만듬
=> TT-355 카카오 로그인 역직렬화 해결

src/main/java/com/twentythree/peech/user/controller/UserController.java, src/main/java/com/twentythree/peech/user/domain/UserFetcher.java, src/main/java/com/twentythree/peech/user/dto/response/GetUserInformationResponseDTO.java, src/main/java/com/twentythree/peech/user/repository/UserRepository.java, src/main/java/com/twentythree/peech/user/service/UserService.java, src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
유저 정보 조회 endpoint 개방
유저 정보 조회시 닉네임을 반환
=> TT-351 get user by token

src/main/java/com/twentythree/peech/security/config/SecurityConfig.java
- 기존의 방식은 권한인증이 필요해서 일단은 swagger는 필터 거치지 않도록 수정
=> bug: swagger 401에러

src/main/java/com/twentythree/peech/common/dto/response/WrappedResponseBody.java, src/main/java/com/twentythree/peech/user/controller/UserController.java
WrappedResponseBody클래스를 만들어서 responseBody를 감싸서 status code를 포함하도록 만듦
=> TT-359 회원가입에서 sign up finished에 맞춰 상태를 body에 담아서 전송

src/main/java/com/twentythree/peech/security/jwt/JWTAuthenticationProvider.java, src/main/java/com/twentythree/peech/user/service/UserService.java, src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java
AuthProvider에서 db를 통해 유저정보를 가져와 회원가입 완성 유무를 판단 후 PENDING인 경우 잘못된 접근으로 처리함
=> TT-346 유저 추가정보 확인 로직 추가

src/main/java/com/twentythree/peech/paragraph/client/GPTClient.java
GPT 엔드포인트라 우리 엔드포인트가 아닌데 잘못 생각함
=> v1.1 -> v 1

src/main/resources/spring-logback.xml
기본 log 파일을 logback.log로 만드는 것을 제거
=> TT-379 로그 파일 일자별 생성

src/main/java/com/twentythree/peech/common/utils/JWTUtils.java, src/main/java/com/twentythree/peech/security/config/JWTSecurityConfig.java, src/main/java/com/twentythree/peech/security/config/SecurityConfig.java, src/main/java/com/twentythree/peech/security/exception/JWTAuthenticationException.java, src/main/java/com/twentythree/peech/security/exception/LoginExceptionCode.java, src/main/java/com/twentythree/peech/security/filter/JWTAuthenticationFilter.java, src/main/java/com/twentythree/peech/security/handler/JWTAuthAccessDeniedHandler.java, src/main/java/com/twentythree/peech/security/handler/JWTAuthEntryPoint.java, src/main/java/com/twentythree/peech/security/jwt/JWTUserDetails.java, src/main/java/com/twentythree/peech/security/jwt/JWTUserDetailsService.java
- JWTUserDetailsService 클래스에서 UserRepository를 통해 해당 userEntity를 조회 후, 이를 기반으로 Authentication 객체를 생성
- PENDING 여부도 해당 클래스에서 확인
- filter를 거치는 과정에서 발생할 수 있는 Error들을 LoginExceptionCode로 따로 정의함
=> TT-346 filter 예외처리 수정

src/main/java/com/twentythree/peech/common/utils/JWTUtils.java, src/main/java/com/twentythree/peech/security/config/SecurityConfig.java, src/main/java/com/twentythree/peech/security/jwt/JWTUserDetailsService.java
- userDetail에서 추가정보 입력 uri로 요청시 PENDING에 대한 조건 처리를 안하도록 처리해줌
=> TT-346 추가정보 입력에 대한 예외처리

src/main/java/com/twentythree/peech/user/controller/UserController.java, src/main/java/com/twentythree/peech/user/domain/UserFetcher.java, src/main/java/com/twentythree/peech/user/dto/LoginBySocial.java, src/main/java/com/twentythree/peech/user/service/UserService.java, src/main/java/com/twentythree/peech/user/service/UserServiceImpl.java, src/main/java/com/twentythree/peech/user/validator/UserValidator.java, src/main/java/com/twentythree/peech/user/validator/UserValidatorImpl.java
singed up finished 가 finished인 유저는 status code가 200으로 가야 한다.
=> TT-380 이미 완전 가입된 유저가 로그인 할 떄

src/main/java/com/twentythree/peech/common/app/AppInfo.java, src/main/java/com/twentythree/peech/common/app/AppInfoController.java
=> TT-381 app info

src/main/java/com/twentythree/peech/security/config/SecurityConfig.java
=> TT-381 security setting 변경

src/main/java/com/twentythree/peech/usagetime/constant/UsageConstantValue.java
=> fix: TT-382 max autio time 25분

src/main/java/com/twentythree/peech/auth/controller/AuthController.java, src/main/java/com/twentythree/peech/auth/service/ReissueAccessAndRefreshTokenService.java, src/main/java/com/twentythree/peech/security/config/SecurityConfig.java, src/main/java/com/twentythree/peech/security/dto/RequestInformationDTO.java, src/main/java/com/twentythree/peech/security/filter/JWTAuthenticationFilter.java
- reissue 역시 validate가 필요하기에 filter를 거치게 수정
=> TT-385 reissue 요청시 안되는 문제 발생

.github/workflows/cd_prod.yml, .github/workflows/ci_prod.yml, .github/workflows/cicd_dev.yml, build.gradle, src/main/java/com/twentythree/peech/common/utils/ExtractDuration.java, src/main/java/com/twentythree/peech/common/utils/FileUtils.java, src/main/java/com/twentythree/peech/config/FFMPEGConfig.java, src/main/java/com/twentythree/peech/script/stt/controller/STTController.java, src/main/java/com/twentythree/peech/script/stt/dto/request/STTRequest2DTO.java, src/main/java/com/twentythree/peech/script/stt/service/AudioChecker.java, src/main/java/com/twentythree/peech/script/stt/service/ProcessSTTService.java, src/main/resources/application.yml
웹에서 STT를 사용하기 위해 base64로 인코딩된 파일을 받아와 다시 음성 파일로 변경(.webm)
ffmpeg를 이용하여 음성 파일의 길이를 측정
=> TT-402 웹에서 STT동작 및 음성 길이 확인

.github/workflows/cd_prod.yml, .github/workflows/cicd_dev.yml, Dockerfile
ec2의 ffmpeg을 docker volume으로 등록
=> TT-402 docker 에서 ffmpeg

src/main/java/com/twentythree/peech/script/stt/service/ProcessSTTService.java
=> TT-403 ffmpeg 로직 임시 제거

src/main/java/com/twentythree/peech/script/stt/service/ProcessSTTService.java
ffmpeg을 사용하면서 요청에 time을 받을 필요가 없게 됨으로 변경
=> TT-406 time을 totalRealSeconds로 변경

.github/workflows/cd_prod.yml, .github/workflows/ci_prod.yml, .github/workflows/cicd_dev.yml, src/main/java/com/twentythree/peech/config/WebConfig.java, src/main/resources/application.yml
- dev와 prod가 허용하는 origin이 달라 환경변수화를 통해서 구분함
=> TT-411 cors origin 환경변수

src/main/java/com/twentythree/peech/feedback/application/FeedbackService.java, src/main/java/com/twentythree/peech/feedback/domain/FeedbackDomain.java, src/main/java/com/twentythree/peech/feedback/domain/FeedbackMapper.java, src/main/java/com/twentythree/peech/feedback/entity/Feedback.java, src/main/java/com/twentythree/peech/feedback/infrastructure/FeedbackMapperImpl.java, src/main/java/com/twentythree/peech/feedback/infrastructure/JpaFeedbackRepository.java, src/main/java/com/twentythree/peech/feedback/presentation/FeedbackController.java, src/main/java/com/twentythree/peech/feedback/value/request/CreateFeedbackRequestDTO.java
feedback domain entity 생성 feedback id, feedback message와 사용자 정보를 가짐
feedback domain entity를 저장하는 feedback mapper 구현
feedback message로 feedback을 생성하는 applicaiton 로직
feedback 생성을 위한 endpoint 개방
=> TT-415 피드백 받기

src/main/java/com/twentythree/peech/common/utils/ScriptUtils.java, src/main/java/com/twentythree/peech/script/client/ClovaParagraphClient.java, src/main/java/com/twentythree/peech/script/controller/ScriptController.java, src/main/java/com/twentythree/peech/script/dto/ParagraphExpectedTimeDTO.java, src/main/java/com/twentythree/peech/script/dto/request/ExpectedTimeRequestDTO.java, src/main/java/com/twentythree/peech/script/dto/request/RequestClovaDTO.java, src/main/java/com/twentythree/peech/script/service/ScriptService.java, src/main/java/com/twentythree/peech/script/stt/dto/response/ParagraphDivideResponseDto.java
=> TT-470 예상시간 입력 방식 변경
